### PR TITLE
feat: unplugin (webpack)

### PR DESCRIPTION
**Pull request by Aslemammad**
This PR tries to enable tool-agnosticism in telefunc.

It's up to @brillout to review, it's not ready & I don't think it's ready for a review.

### CODE REVIEW

**Comment by brillout** [comment]
Nice, does it already work for Vite?

**Comment by Aslemammad** [comment]
@brillout Yes, for now!

**Comment by brillout** [comment]
👍 Let's check if it works with other frameworks. I believe there are some Vite specific code in the code though.

**Comment by Aslemammad** [comment]
Nope! need to research more about and also test it myself! that's why it's not ready yet!

**Comment by brillout** [comment]
👌

**Comment by brillout** [comment]
All tests are now passing :-). (Not on Windows nor MacOS though; no clue why 🤔.)

I'll continue reviewing tomorrow, and I'll dig about why the tests are not passing on Windows/MacOS. Confident I'll be able to merge tomorrow.

**Pull request merged**
